---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: fedora_package${SUFFIX}
    image: ajxb/fedora:latest
    command: "/usr/lib/systemd/systemd"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      library: ${MOLECULE_PROJECT_DIRECTORY}/library
      collections_path: ${MOLECULE_PROJECT_DIRECTORY}/collections
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/roles
      remote_tmp: /tmp
      stdout_callback: debug
      remote_user: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: ${MOLECULE_PROJECT_DIRECTORY}/collections
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
verifier:
  name: ansible
